/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import com.sun.glass.events.KeyEvent;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.regex.Pattern;
import static javax.print.attribute.Size2DSyntax.MM;
import static javax.swing.BorderFactory.createTitledBorder;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.border.Border;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
/**
 *
 * @author MF
 */
public class Form_Persetujuan_Pinjaman extends javax.swing.JFrame {
private Dimension screensize;
 Connection con;
Statement sta;
Statement stat;
ResultSet rs;
DefaultTableModel tbm;
String tanggal;
    private Border createTitleBorder;
    /**
     * Creates new form Form_Persetujuan_Pinjaman
     */
    public Form_Persetujuan_Pinjaman() {
        initComponents();
        
        datesekarang.setEnabled(false);
        panel_data_anggota.setVisible(false);
        btnsetuju.setEnabled(false);
        btntidak.setEnabled(false);
        btnbatal.setEnabled(false);
        panel_data.setBorder(createTitledBorder("DATA"));
        panel_data_anggota.setBorder(createTitledBorder("ANGGOTA"));
        panel_tabel_pinjaman.setBorder(createTitledBorder("PINJAMAN"));
        txtidpinjaman.setEnabled(false);
        txtid_anggota.setEnabled(false);
        txtbesarsimpanan.setEnabled(false);
        
        
        screensize = Toolkit.getDefaultToolkit().getScreenSize();
          setLocation((screensize.width / 2) - (getSize().width / 2), (screensize.height / 2) - (getSize().height / 2));
          
         koneksi DB = new koneksi();
            DB.config();
            con = DB.con;
            sta = DB.stm;
            
            tanggal_sekarang();
            masuktabel();
    }

    private void tanggal_sekarang() {
        Date date = new Date();
        datesekarang.setDate(date);
                
    }
    
    private void masuktabelanggota(){
            try{
                sta = con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_UPDATABLE);
                tbm = new DefaultTableModel();
                tbm.addColumn("Nama");
                tbm.addColumn("Alamat");
                tbm.addColumn("Jen_kel");
                tbm.addColumn("Status");
                tbm.addColumn("No Telp");
                tbm.addColumn("Keterangan");
                
                tbl_anggota.setModel(tbm);
                rs = sta.executeQuery("SELECT nama,alamat,j_kel,status,no_telp,ket FROM anggota WHERE id_anggota='"+ txtid_anggota.getText() +"'");
                while (rs.next()){
                    tbm.addRow(new Object[]{
                    rs.getString("nama"),
                    rs.getString("alamat"),
                    rs.getString("j_kel"),
                    rs.getString("status"),
                    rs.getString("no_telp"),
                    rs.getString("ket"),
                    
                });
                    tbl_anggota.setModel(tbm);
                    }
                }catch(Exception e){
                        JOptionPane.showMessageDialog(rootPane,"Gagal"+e);
                        
                    }
    }
    
    private void masuktabel() {
       try{
                sta = con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_UPDATABLE);
                tbm = new DefaultTableModel();
                tbm.addColumn("ID Pinjaman");
                tbm.addColumn("ID Anggota");
                tbm.addColumn("Besar Pinjaman");
                tbm.addColumn("Tgl Pengajuan");
                tbm.addColumn("KET");
                
                jTable1.setModel(tbm);
                rs = sta.executeQuery("SELECT * FROM pinjaman WHERE ket='Belum Disetujui'");
                while (rs.next()){
                    tbm.addRow(new Object[]{
                    rs.getString("id_pinjaman"),
                    rs.getString("id_anggota"),
                    rs.getString("besar_pinjaman"),
                    rs.getString("tgl_pengajuan_pinjaman"),
                    rs.getString("ket"),
                    
                });
                    jTable1.setModel(tbm);
                    }
                }catch(Exception e){
                        JOptionPane.showMessageDialog(rootPane,"Gagal"+e);
                        
                    }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panel_data = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtid_anggota = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtbesar_pinjaman = new javax.swing.JTextField();
        txtidpinjaman = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtbesarsimpanan = new javax.swing.JTextField();
        btnsetuju = new javax.swing.JButton();
        btntidak = new javax.swing.JButton();
        btnbatal = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        datesekarang = new com.toedter.calendar.JDateChooser();
        panel_tabel_pinjaman = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txtcari = new javax.swing.JTextField();
        btncari = new javax.swing.JButton();
        panel_data_anggota = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_anggota = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("FORM PERSETUJUAN");

        panel_data.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel2.setText("ID Pinjaman");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel3.setText("ID Anggota");

        txtid_anggota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtid_anggotaActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel4.setText("Besar Pinjaman");

        jButton2.setText("TAMPILKAN");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel6.setText("Besar Simpanan Sukarela");

        txtbesarsimpanan.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtbesarsimpananPropertyChange(evt);
            }
        });

        btnsetuju.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnsetuju.setText("SETUJU");
        btnsetuju.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsetujuActionPerformed(evt);
            }
        });

        btntidak.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btntidak.setText("TIDAK");
        btntidak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntidakActionPerformed(evt);
            }
        });

        btnbatal.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnbatal.setText("BATAL");
        btnbatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbatalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_dataLayout = new javax.swing.GroupLayout(panel_data);
        panel_data.setLayout(panel_dataLayout);
        panel_dataLayout.setHorizontalGroup(
            panel_dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_dataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel2)
                        .addComponent(jLabel4)
                        .addComponent(txtbesar_pinjaman, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                        .addGroup(panel_dataLayout.createSequentialGroup()
                            .addGroup(panel_dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtidpinjaman, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtid_anggota, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton2))
                        .addComponent(jLabel6)
                        .addComponent(txtbesarsimpanan))
                    .addGroup(panel_dataLayout.createSequentialGroup()
                        .addComponent(btnsetuju)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btntidak)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnbatal)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_dataLayout.setVerticalGroup(
            panel_dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_dataLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtidpinjaman, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtid_anggota, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtbesar_pinjaman, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtbesarsimpanan, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panel_dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnsetuju)
                    .addComponent(btntidak)
                    .addComponent(btnbatal))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel5.setText("Tanggal : ");

        datesekarang.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        datesekarang.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                datesekarangPropertyChange(evt);
            }
        });

        panel_tabel_pinjaman.setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        txtcari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcariKeyPressed(evt);
            }
        });

        btncari.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btncari.setText("CARI");
        btncari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncariActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_tabel_pinjamanLayout = new javax.swing.GroupLayout(panel_tabel_pinjaman);
        panel_tabel_pinjaman.setLayout(panel_tabel_pinjamanLayout);
        panel_tabel_pinjamanLayout.setHorizontalGroup(
            panel_tabel_pinjamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_tabel_pinjamanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_tabel_pinjamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 479, Short.MAX_VALUE)
                    .addGroup(panel_tabel_pinjamanLayout.createSequentialGroup()
                        .addComponent(txtcari, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btncari)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panel_tabel_pinjamanLayout.setVerticalGroup(
            panel_tabel_pinjamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_tabel_pinjamanLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panel_tabel_pinjamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcari, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btncari, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panel_data_anggota.setBackground(new java.awt.Color(255, 255, 255));

        tbl_anggota.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tbl_anggota);

        javax.swing.GroupLayout panel_data_anggotaLayout = new javax.swing.GroupLayout(panel_data_anggota);
        panel_data_anggota.setLayout(panel_data_anggotaLayout);
        panel_data_anggotaLayout.setHorizontalGroup(
            panel_data_anggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_data_anggotaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        panel_data_anggotaLayout.setVerticalGroup(
            panel_data_anggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_data_anggotaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton1.setText("KELUAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panel_data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(datesekarang, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(panel_tabel_pinjaman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(78, 78, 78)
                                .addComponent(jLabel1))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(panel_data_anggota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(215, 215, 215)
                        .addComponent(jButton1)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(datesekarang, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(panel_data, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panel_tabel_pinjaman, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panel_data_anggota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void datesekarangPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_datesekarangPropertyChange
    if (datesekarang.getDate()!=null){
            SimpleDateFormat simpleDateFormat = new SimpleDateFormat("yyyy-MM-dd");
            tanggal = simpleDateFormat.format(datesekarang.getDate());}        
        // TODO add your handling code here:
    }//GEN-LAST:event_datesekarangPropertyChange

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        panel_data_anggota.setVisible(true);
        masuktabelanggota();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        btnsetuju.setEnabled(true);
        btntidak.setEnabled(true);
        btnbatal.setEnabled(true);
         
        txtidpinjaman.setText(tbm.getValueAt(jTable1.getSelectedRow(), 0)+"");
        txtid_anggota.setText(tbm.getValueAt(jTable1.getSelectedRow(), 1)+"");
        txtbesar_pinjaman.setText(tbm.getValueAt(jTable1.getSelectedRow(), 2)+"");
        
         try {
            String sql;
            sql = ("SELECT SUM(besar_simpanan) FROM simpanan WHERE id_anggota='"+ txtid_anggota.getText() +"' AND nm_simpanan='Simpanan Sukarela'");
            rs = sta.executeQuery(sql);
            while (rs.next()) {
                String besar = rs.getString("SUM(besar_simpanan)");
              txtbesarsimpanan.setText(besar);
            } 
        } catch (Exception e) {
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnbatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbatalActionPerformed
        new Form_Persetujuan_Pinjaman().setVisible(true);
        this.dispose();
              
        // TODO add your handling code here:
    }//GEN-LAST:event_btnbatalActionPerformed

    private void txtid_anggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtid_anggotaActionPerformed
        
        // TODO add your handling code here:
    }//GEN-LAST:event_txtid_anggotaActionPerformed

    private void btncariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncariActionPerformed
          TableRowSorter sorter = new TableRowSorter(jTable1.getModel());
        jTable1.setRowSorter(sorter);
        sorter.setRowFilter(RowFilter.regexFilter(Pattern.compile("(?i).*"+ txtcari.getText()+".*",Pattern.CASE_INSENSITIVE | Pattern.DOTALL).toString()));
        jTable1.setSelectionMode(1);
        // TODO add your handling code here:
    }//GEN-LAST:event_btncariActionPerformed

    private void txtcariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcariKeyPressed
         if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btncariActionPerformed(new ActionEvent(evt.getSource(), evt.getID(), "Key Press Login"+ ""));
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcariKeyPressed

    private void btnsetujuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsetujuActionPerformed
            if (txtidpinjaman.getText().equals("") ||
                 txtid_anggota.getText().equals("") || 
                    txtbesar_pinjaman.getText().equals("")       
                    ) 
            {
                JOptionPane.showMessageDialog(rootPane, "Masukkan Semua Data");
            } else {
                try {
                    String sql;
                    sql = "UPDATE pinjaman SET tgl_acc_peminjaman='" +tanggal+ "',tgl_pinjaman='" +tanggal+ "',ket='Disetujui' WHERE id_pinjaman='" +txtidpinjaman.getText()+ "'";
                    sta.executeUpdate(sql);
                    JOptionPane.showMessageDialog(rootPane, "BERHASIL");
                    new Form_Persetujuan_Pinjaman().setVisible(true);
                    this.dispose();
                } catch (Exception e) {
                    System.out.println(""+ e.getMessage());
                }
            }
            
            
        // TODO add your handling code here:
    }//GEN-LAST:event_btnsetujuActionPerformed

    private void btntidakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntidakActionPerformed
         if (txtidpinjaman.getText().equals("") ||
                 txtid_anggota.getText().equals("") || 
                    txtbesar_pinjaman.getText().equals("")       
                    ) 
            {
                JOptionPane.showMessageDialog(rootPane, "Masukkan Semua Data");
            } else {
                try {
                    String sql;
                    sql = "UPDATE pinjaman SET ket='Tidak Disetujui' WHERE id_pinjaman='" +txtidpinjaman.getText()+ "'";
                    sta.executeUpdate(sql);
                    JOptionPane.showMessageDialog(rootPane, "BERHASIL DITOLAK");
                    new Form_Persetujuan_Pinjaman().setVisible(true);
                    this.dispose();
                    
                } catch (Exception e) {
                    System.out.println(""+ e.getMessage());
                }
            }
        // TODO add your handling code here:
    }//GEN-LAST:event_btntidakActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtbesarsimpananPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtbesarsimpananPropertyChange

        // TODO add your handling code here:
    }//GEN-LAST:event_txtbesarsimpananPropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Persetujuan_Pinjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Persetujuan_Pinjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Persetujuan_Pinjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Persetujuan_Pinjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_Persetujuan_Pinjaman().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbatal;
    private javax.swing.JButton btncari;
    private javax.swing.JButton btnsetuju;
    private javax.swing.JButton btntidak;
    private com.toedter.calendar.JDateChooser datesekarang;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel panel_data;
    private javax.swing.JPanel panel_data_anggota;
    private javax.swing.JPanel panel_tabel_pinjaman;
    private javax.swing.JTable tbl_anggota;
    private javax.swing.JTextField txtbesar_pinjaman;
    private javax.swing.JTextField txtbesarsimpanan;
    private javax.swing.JTextField txtcari;
    private javax.swing.JTextField txtid_anggota;
    private javax.swing.JTextField txtidpinjaman;
    // End of variables declaration//GEN-END:variables
}
